version: '3.1'
services:
  bigos-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5401:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local